import os
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# File and parameter settings
output_dir = r"C:\Users\admin\Desktop\Python_proj\ALL_RESULT\GPT\T2S1\backup6"
resolution = 0.9
csv_filename = f'grayscale_line_res{resolution}.csv'
csv_path = os.path.join(output_dir, csv_filename)

# Core function: Get line grayscale values
def get_line_grayscale():
    """
    Reads grayscale values from the CSV file generated by py1.py.
    Returns:
        np.ndarray: Grayscale values.
    """
    import csv
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"CSV file not found: {csv_path}")
    with open(csv_path, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            arr = np.array([int(float(x)) for x in row])
            return arr
    return None

# Core function: Calculate μ_eq
def calculate_μeq(grayscale_values) -> np.ndarray:
    """
    Example μ_eq calculation: Normalize grayscale values to [0, 1].
    Args:
        grayscale_values (np.ndarray): Array of grayscale values.
    Returns:
        np.ndarray: Normalized grayscale values (μ_eq).
    """
    min_val = grayscale_values.min()
    max_val = grayscale_values.max()
    if max_val - min_val == 0:
        return np.zeros_like(grayscale_values, dtype=float)
    mu_eq = (grayscale_values - min_val) / (max_val - min_val)
    return mu_eq

# Plot function: Plot μ_eq curve
def plot_μeq_curve(mu_eq_arr):
    plt.figure(figsize=(8, 4))
    plt.plot(mu_eq_arr, marker='o')
    plt.title(r'$\mu_{eq}$ Curve Along Line')
    plt.xlabel('Point Index')
    plt.ylabel(r'$\mu_{eq}$ (Normalized Grayscale)')
    plt.grid(True)
    plt.tight_layout()
    plot_save_path = os.path.join(output_dir, f'mu_eq_curve_res{resolution}.png')
    plt.savefig(plot_save_path, dpi=150)
    print(f"μ_eq curve plot saved to: {plot_save_path}")
    plt.show()

# Main program execution
def main():
    grayscale_values = get_line_grayscale()
    print("Grayscale values read from CSV:", grayscale_values)
    mu_eq = calculate_μeq(grayscale_values)
    print("μ_eq values (first 10):", mu_eq[:10])
    plot_μeq_curve(mu_eq)

if __name__ == '__main__':
    main()
